version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  server:
    build: ./backend
    container_name: job_importer_server
    restart: always
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URI: "mongodb+srv://neeraj:neeraj123@cluster.3t2lvax.mongodb.net/knotask?retryWrites=true&w=majority"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      IMPORT_EVENTS_CHANNEL: import-events
      QUEUE_NAME: job_import_queue
      WORKER_CONCURRENCY: 5
      BATCH_SIZE: 50
      PORT: 4000
    ports:
      - "4000:4000"

  worker:
    build: ./backend
    container_name: job_importer_worker
    command: ["node", "worker.js"]
    restart: always
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URI: "mongodb+srv://neeraj:neeraj123@cluster.3t2lvax.mongodb.net/knotask?retryWrites=true&w=majority"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      IMPORT_EVENTS_CHANNEL: import-events
      QUEUE_NAME: job_import_queue
      WORKER_CONCURRENCY: 5
      BATCH_SIZE: 50

  cron:
    build: ./backend
    container_name: job_importer_cron
    command: ["node", "cron.js"]
    restart: always
    depends_on:
      - redis
      - mongo
    environment:
      MONGO_URI: "mongodb+srv://neeraj:neeraj123@cluster.3t2lvax.mongodb.net/knotask?retryWrites=true&w=majority"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      IMPORT_EVENTS_CHANNEL: import-events
      QUEUE_NAME: job_import_queue
      BATCH_SIZE: 50
      CRON_EXPRESSION: "0 * * * *"

volumes:
  mongo_data:
